[app]
title = 智能代理共享
package.name = proxyshare
package.domain = org.example.proxyshare
source.dir = .
source.include_exts = py,png,jpg,kv,atlas
source.include_patterns = assets/*,images/*
version = 1.0
requirements = python3,kivy
orientation = portrait
fullscreen = 0
android.api = 33
android.minapi = 21
android.sdk = 24
android.ndk = 25b
android.archs = arm64-v8a, armeabi-v7a
android.allow_backup = True
android.permissions = INTERNET, ACCESS_NETWORK_STATE, ACCESS_WIFI_STATE
android.presplash_color = #667eea
android.presplash_lottie = 
android.service = 
android.entrypoint = org.kivy.android.PythonActivity
android.manifest.intent_filters = 
android.manifest.placeholders = 
android.manifest.application_meta_data = 
android.manifest.activity_meta_data = 
android.manifest.provider = 
android.manifest.uses_feature = 
android.manifest.uses_library = 
android.manifest.queries = 
android.manifest.uses_permission = 
android.manifest.uses_permission_sdk23 = 
android.manifest.uses_permission_maxsdk = 
android.manifest.receivers = 
android.manifest.services = 
android.manifest.providers = 
android.manifest.activities = 
android.manifest.application_attrs = 
android.manifest.activity_attrs = 
android.manifest.service_attrs = 
android.manifest.receiver_attrs = 
android.manifest.provider_attrs = 
android.manifest.meta_data = 
android.manifest.uses_cleartext_traffic = 
android.manifest.allow_native_debug = 
android.manifest.debuggable = 
android.manifest.network_security_config = 
android.manifest.uses_permission_sdk = 
android.manifest.uses_feature_required = 
android.manifest.uses_feature_feature = 
android.manifest.queries_intent = 
android.manifest.queries_package = 
android.manifest.queries_provider = 
android.manifest.uses_permission_name = 
android.manifest.uses_permission_max_sdk_version = 
android.manifest.uses_permission_uses_permission_sdk = 
android.manifest.uses_permission_uses_permission_name = 

[buildozer]
log_level = 2
warn_on_root = 1
